# Generated by Django 5.2.8 on 2025-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price'),
        ),
    ]
