# Generated by Django 5.2.8 on 2025-12-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/previews/', verbose_name='Image'),
        ),
    ]
