# Generated by Django 5.2.8 on 2025-12-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_good_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory', verbose_name='Subcategory'),
        ),
    ]
