# Generated by Django 5.2.8 on 2025-12-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_a',
            new_name='created_at',
        ),
    ]
