# Generated by Django 5.2.8 on 2025-12-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_basket_basketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='quantity',
        ),
    ]
