# Generated by Django 5.2.8 on 2025-12-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_basketitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
